run: clear build run-dist

run-dist:
	sh ./build/install/app/bin/app/

run-dist2:
	.\\build\\install\\app\\bin\\app

clear:
	gradlew clean

build:
	gradlew installDist

checkstyle:
	gradlew checkstyleMain